language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
cache:
- bundler
script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
- bin/rails db:migrate
- bundle exec rspec
services: 
- postgresql

