language: ruby
rvm:
- 2.5.0
cache:
- bundler
script:
- bundle install --jobs=3 --retry=3
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: Z3BljZ48XZa0zatKQhKY7yApaWGPGkz/Ul6M7aOHn327P8pWudJoDbLzk/+wJLORT+YrBMXzMjUyT4+gijNsfwS2Rx60nprdLqf4/BpTMxfO9WBGQcsWe2PEEt7Bm6t1jMsqzxsBy1O7v04UxisX9vKkk1rw4Ivnb+Tem/fD8LMtTOSHnH3lDkvU2v1VAgIakLXXgRyGdpyFJEhK/W7x/0aPHeIvNFZpJzLUHCN05gzwERVw0x1lVXfq0CH/mJnSBwZH8UuaXrJLdmF99XgKueJFZkzTjrHAa5N0NrgaaKynF4J59DGOT+8ptyabFnyiqCyF2zq5EdpoG3HeokeLYMKVsVRFyj2ZNPlO6pVkubY84gZlV5k9onvMwLkqkcikxFH+8aO+nIXMkvq/SnZ7348MUikHJk/F+bPZG0TaDDH2p2PmCQAIAQ2GKSyWJmZ2I3PQdVSC7587lpiiLK5+KVboUdyVyRvJ+DuSnIhGIiu93i1aD3dR1mTBRL3JZJoqdBwvSBoRcJur29rQhiBvQu93ykCjtgDP4X4RePS7v0+BteXP9vpx6G0rlDcspZX/44Rxs42pCQWWTU3VitM2s6K+MfPmQUcieo9Vxc0HiF2QZ0H7W/X/G37PbGtafA5Op5ceek1vl9Gu9pEhRc5Pkc8vBKVqwq7sZNHnV9DLNCQ=
  run: rake db:migrate
  app: acebook-dragons
  on:
    repo: CazaBelle/acebook-rails-smoking-dragons
