language: ruby
rvm:
- 2.5.0
cache:
- bundler
script:
- bundle install --jobs=3 --retry=3
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: LqcSaGrA83bGJyeYOtkya66AgDuO+VRouBR8pNdX7wJksilKWIcTyrWhBtIpv/uKX+alT7Uzw7dPnDyfpbdlknQWP05ViSEHjczJXviVn14Kd/hEPnNEC8lOsMh9KKkCILEY6KvREdJoPf0uD3gM5z9L9/okiBo36bLPbcQEcudivZiikxqqGxmRrF3wtG0snAfhWCwmhj94JuCmlu8IACt4folqjGH82gHTYLr+jeY/njUvdI8ib+UvTs7bLH6oAKYLQ8Y3zKo8Vf7MbhlQkuBeXPgqBb/cmvVxmBEcKU6MpyMevMXfdyjYsl13K0U4kSxdfGYfWGTqZp06kzMhbEY7Ej+loGmOeV1Kv7wrAlMXm6V8LlA4lTw/KPFuyAZJcT+E0KM8wev4sD/2g172SqWEctXq97W9KUafIcvYYOjvI2QtdXBuMcYImQ9saP4oDyceDvwprVN2c2rRnWfP1lGlW+yen1CFcYumYzuve2uyWQMsVRRktCEewK7GUyf5igWp4lSaZHVoOMM1XWQh4fKT9ZohorO8aZXK5Euva4IXn1EeG2itfz3gn6LC5RR31oMPwn2qUp/mTPZPPa/TIRnBo7MX5faU474uhwxiOKo57r4jK1UgQ5RRInl5T2sP1IQtbhYP2Gff6LopAN7l7wGc/LmUCpzuQMy7yZVDMTI=
  app: acebook-smoking-dragons
  on:
    repo: CazaBelle/acebook-rails-smoking-dragons
